import Head from 'next/head'

import { PageWrapper } from '../shared/styles'
import TokenTable from '../components/TokenTable'

const tokens = [
  {
    address: '0x0000000000000000000000000000456E65726779',
    symbol: 'VTHO',
    name: 'VeChain Thor'
  },
  {
    address: '0x0ce6661b4ba86a0ea7ca2bd86a0de87b0b860f14',
    symbol: 'OCE',
    name: 'OceanEx'
  },
  {
    address: '0x67fD63f6068962937EC81AB3Ae3bF9871E524FC9',
    symbol: 'JUR',
    name: 'Jur'
  },
  {
    address: '0x67fd63f6068962937ec81ab3ae3bf9871e524fc9',
    symbol: 'VEED',
    name: 'VIMworld'
  },
  {
    address: '0x5db3c8a942333f6468176a870db36eef120a34dc',
    symbol: 'SHA',
    name: 'Safe Haven'
  },
  {
    address: '0xacc280010b2ee0efc770bce34774376656d8ce14',
    symbol: 'HAI',
    name: 'HackenAI'
  },
  {
    address: '0xf8e1faa0367298b55f57ed17f7a2ff3f5f1d1628',
    symbol: 'EHrT',
    name: 'Eight Hours Token'
  },
  {
    address: '0x1b8ec6c2a45cca481da6f243df0d7a5744afc1f8',
    symbol: 'DBET',
    name: 'Decent.bet'
  },
]

export default function Home() {
  return (
    <PageWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Vexchange Overview
      <TokenTable tokens={tokens} />
    </PageWrapper>
  )
}
