import { useEffect, useState } from 'react'
import Big from 'big.js'
import Head from 'next/head'
import axios from 'axios'
import CoinGecko from 'coingecko-api'
import styled from '@emotion/styled'
import { Flex, Box, Text } from 'rebass'

import { formatCurrency } from '../utils'
import { allTokens } from '../utils/constants/tokens'
import { PageWrapper } from '../shared/styles'
import TokenTable from '../components/TokenTable'
import Card from '../components/Card'

const OrangeBG = styled.div`
  position: absolute;
  top: -200px;
  left: 0px;
  right: 0px;
  pointer-events: none;
  height: 200vh;
  mix-blend-mode: color;
  background: radial-gradient(50% 50% at 50% 50%, rgb(217, 41, 33) 0%, rgba(255, 255, 255, 0) 100%);
  transform: translateY(-150vh);
  max-width: 100vw !important;
`

const LargeText = styled.p`
  font-size: 32px;
  margin: 0;
`

const Label = styled.span`
  color: rgb(108, 114, 132);
  box-sizing: border-box;
  margin: 0px;
  min-width: 0px;
  font-weight: 500;
  font-size: 16px;
`

const CoinGeckoClient = new CoinGecko();

export default function Home() {
  const [price, setPrice] = useState(0)
  const [tokens, setTokens] = useState([])
  const [tvl, setTVL] = useState(0)
  const [vol, setVol] = useState(0)

	useEffect(() => {
		const getPrice = async () => {
			const { data } = await CoinGeckoClient.simple.price(
				{
					ids: ['vechain'],
					vs_currencies: ['usd'],
			});

			setPrice(data.vechain.usd)
		}

    getPrice()
	}, [])

	useEffect(() => {
    const getData = () => {
      const promises = allTokens.map(async (item) => {
        const { data } = await axios.get(`/api/${item.address}`)
        item = { ...data, ...item }

        return item
      })

      Promise.all(promises).then(data => {
        setTokens(data)
      })
    }

    if (tokens.length === 0) {
      getData()
    }
	}, [tokens])

  useEffect(() => {
    const calculate = () => {
      const stats = tokens.reduce((acc, curr) => {
        return {
          tvl: acc.tvl.plus(Big(curr.reserves)),
          vol: acc.vol.plus(Big(curr.volume))
        }
      }, { tvl: new Big(0), vol: new Big(0)})

      setTVL(stats.tvl.toString())
      setVol(stats.vol.toString())
    }

    if (tokens.length !== 0) {
      calculate()
    }
  }, [tokens])

  return (
    <PageWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <OrangeBG />
      <Text mb={3}>Vexchange Overview</Text>
      { tokens.length === 0 
        ? (
        <div>Loading...</div>
        ) : (
          <>
            <Flex mx={-3} mb={4}>
              <Box width={1/2} px={3}>
                <Card>
                  <Label>TVL</Label>
                  <LargeText>{ formatCurrency((tvl * price).toFixed(2)) }</LargeText>
                </Card>
              </Box>
              <Box width={1/2} px={3}>
                <Card>
                  <Label>Volume 24H</Label>
                  <LargeText>{ formatCurrency((vol * price).toFixed(2)) }</LargeText>
                </Card>
              </Box>
              <Box width={1/2} px={3}>
                <Card>
                  <Label>Fees 24H</Label>
                  <LargeText>{ formatCurrency(((vol * price) * 0.01).toFixed(2)) }</LargeText>
                </Card>
              </Box>
            </Flex>
            <Text mb={3}>Top Tokens</Text>
            <TokenTable tokens={tokens} price={price} />
          </>
        )}
    </PageWrapper>
  )
}
